package com.futurethinking.timestampgenius.service
import android.content.Context
import android.graphics.*
import android.view.MotionEvent
import android.view.View
import com.futurethinking.timestampgenius.LayoutConfig
import com.futurethinking.timestampgenius.LineShape
import kotlin.math.abs
class LineEditorView(context:Context,initial:LayoutConfig,private val onSave:(LayoutConfig)->Unit,private val onClose:()->Unit):View(context){
 private var cfg=initial.copy(lines=initial.lines.map{it.copy()}.toMutableList())
 private var selected=0;private var mode=0;private var moved=false;private var dx=0f;private var dy=0f;private var dl=0f;private var dt=0f;private var dw=0f;private var dh=0f
 private val stroke=Paint(1).apply{style=Paint.Style.STROKE;strokeWidth=4f};private val fill=Paint(1);private val txt=Paint(1).apply{color=Color.BLACK;typeface=Typeface.DEFAULT_BOLD;textSize=18f}
 override fun onDraw(c:Canvas){c.drawColor(0x55000000);val l=cfg.boxLeft*width;val t=cfg.boxTop*height;val r=(cfg.boxLeft+cfg.boxWidth).coerceAtMost(1f)*width;val b=(cfg.boxTop+cfg.boxHeight).coerceAtMost(1f)*height;stroke.color=Color.YELLOW;stroke.strokeWidth=6f;c.drawRoundRect(l,t,r,b,18f,18f,stroke);val gap=(b-t)/cfg.lineCount;for(i in 0 until cfg.lineCount){val s=cfg.lines[i];val cy=t+gap*i;val lh=gap*.72f*s.heightFraction;val lw=(r-l)*s.widthFraction;val x=l+(r-l-lw)/2;val y=cy+(gap-lh)/2;stroke.strokeWidth=if(i==selected)7f else 3f;stroke.color=if(i==selected||s.unlocked)Color.YELLOW else Color.WHITE;c.drawRoundRect(x,y,x+lw,y+lh,10f+s.cornerFraction*36,10f+s.cornerFraction*36,stroke);txt.textSize=18f;c.drawText((i+1).toString(),l+8,y+lh/2+6,txt)};drawPanel(c)}
 private fun drawPanel(c:Canvas){val top=height-150f;fill.color=Color.WHITE;c.drawRect(0f,top,width.toFloat(),height.toFloat(),fill);txt.textSize=17f;c.drawText("LINES "+cfg.lineCount,12f,top+25,txt);c.drawText("SPEED "+cfg.scrollSpeed,135f,top+25,txt);c.drawText("LINE "+(selected+1),265f,top+25,txt);button(c,8,top+40,58,top+88,"-");button(c,64,top+40,114,top+88,"+");for(i in 0..9)button(c,120+i*32,top+40,150+i*32,top+88,i.toString());button(c,470,top+40,560,top+88,"UNLOCK");button(c,8,top+98,76,top+145,"W-");button(c,80,top+98,148,top+145,"W+");button(c,152,top+98,220,top+145,"H-");button(c,224,top+98,292,top+145,"H+");button(c,296,top+98,364,top+145,"C");button(c,368,top+98,450,top+145,"SAVE");button(c,454,top+98,width-8,top+145,"CLOSE")}
 private fun button(c:Canvas,l0:Float,t:Float,r:Float,b:Float,s:String){stroke.color=Color.BLACK;stroke.strokeWidth=2f;c.drawRect(l0,t,r,b,stroke);txt.textSize=13f;val tw=txt.measureText(s);c.drawText(s,l0+(r-l0-tw)/2,t+(b-t)/2+5,txt)}
 override fun onTouchEvent(e:MotionEvent):Boolean{when(e.actionMasked){MotionEvent.ACTION_DOWN->{dx=e.x;dy=e.y;dl=cfg.boxLeft;dt=cfg.boxTop;dw=cfg.boxWidth;dh=cfg.boxHeight;moved=false;mode=hit(e.x,e.y);return true};MotionEvent.ACTION_MOVE->{if(abs(e.x-dx)>8||abs(e.y-dy)>8)moved=true;when(mode){1->{cfg.boxLeft=(dl+(e.x-dx)/width).coerceIn(0f,1f-cfg.boxWidth);cfg.boxTop=(dt+(e.y-dy)/height).coerceIn(0f,1f-cfg.boxHeight)};2->{cfg.boxWidth=(dw+(e.x-dx)/width).coerceIn(.25f,.95f);cfg.boxLeft=cfg.boxLeft.coerceAtMost(1f-cfg.boxWidth)};3->{cfg.boxHeight=(dh+(e.y-dy)/height).coerceIn(.18f,.85f);cfg.boxTop=cfg.boxTop.coerceAtMost(1f-cfg.boxHeight)}};invalidate();return true};MotionEvent.ACTION_UP->{if(mode==10)control(e.x,e.y)else if(mode==1&&!moved){val top=cfg.boxTop*height;val gap=cfg.boxHeight*height/cfg.lineCount;selected=((e.y-top)/gap).toInt().coerceIn(0,cfg.lineCount-1);invalidate()};return true}};return true}
 private fun hit(x:Float,y:Float):Int{val l=cfg.boxLeft*width;val t=cfg.boxTop*height;val r=(cfg.boxLeft+cfg.boxWidth)*width;val b=(cfg.boxTop+cfg.boxHeight)*height;return when{y>height-160->10;x in r-35..r+35&&y in t..b->2;y in b-35..b+35&&x in l..r->3;x in l..r&&y in t..b->1;else->10}}
 private fun control(x:Float,y:Float){val top=height-150;if(y<top+38)return;if(y<top+94){when{ x in 8f..62f->setCount(cfg.lineCount-1);x in 64f..116f->setCount(cfg.lineCount+1);x>=120&&x<440->{cfg.scrollSpeed=((x-120)/32).toInt().coerceIn(0,9);invalidate()};x>=470->{cfg.lines[selected].unlocked=!cfg.lines[selected].unlocked;invalidate()}}}else{when{x in 8f..78f->edit(-.08f,0f);x in 80f..150f->edit(.08f,0f);x in 152f..222f->edit(0f,-.08f);x in 224f..294f->edit(0f,.08f);x in 296f..364f->{cfg.lines[selected].cornerFraction=if(cfg.lines[selected].cornerFraction>.5f)0f else 1f;invalidate()};x in 368f..450f->onSave(cfg.copy(lines=cfg.lines.map{it.copy()}.toMutableList()));x>450f->onClose()}}}
 private fun setCount(v:Int){cfg.lineCount=v.coerceIn(1,50);while(cfg.lines.size<cfg.lineCount)cfg.lines+=LineShape();while(cfg.lines.size>cfg.lineCount)cfg.lines.removeAt(cfg.lines.lastIndex);selected=selected.coerceAtMost(cfg.lineCount-1);invalidate()}
 private fun edit(dw0:Float,dh0:Float){val s=cfg.lines[selected];if(s.unlocked){s.widthFraction=(s.widthFraction+dw0).coerceIn(.4f,1f);s.heightFraction=(s.heightFraction+dh0).coerceIn(.35f,1.4f);invalidate()}}
}
